# Generated by Django 5.1.7 on 2025-05-28 05:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addauction',
            name='auction_end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 6, 4, 5, 50, 19, 654591, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
