# Generated by Django 5.1.7 on 2025-05-28 06:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0002_alter_addauction_auction_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addauction',
            name='auction_end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 6, 4, 6, 3, 8, 861102, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
