# Generated by Django 5.1.7 on 2025-05-28 06:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0003_alter_addauction_auction_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addauction',
            name='auction_end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 6, 4, 6, 5, 11, 581730, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
