# Generated by Django 5.1.7 on 2025-05-30 06:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0007_alter_addauction_auction_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addauction',
            name='auction_end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 6, 6, 6, 25, 41, 388663, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
