# Generated by Django 5.1.7 on 2025-06-01 06:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0009_alter_addauction_auction_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addauction',
            name='auction_end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 6, 8, 6, 29, 23, 959671, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
