# Generated by Django 5.1.7 on 2025-06-09 16:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0010_alter_addauction_auction_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addauction',
            name='auction_end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 6, 16, 16, 41, 55, 20837, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
