# Generated by Django 6.0 on 2025-12-04 18:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0013_alter_addauction_auction_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addauction',
            name='auction_end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 12, 11, 18, 14, 41, 129411, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
