# Generated by Django 6.0 on 2025-12-04 18:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0014_alter_addauction_auction_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addauction',
            name='auction_end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 12, 11, 18, 21, 52, 887472, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
