# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestProfil():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_profil(self):
        self.driver.get("http://127.0.0.1:8000/")
        self.driver.set_window_size(890, 910)
        self.driver.find_element(By.LINK_TEXT, "Login").click()
        self.driver.find_element(By.ID, "id_username").send_keys("1234")
        self.driver.find_element(By.ID, "id_password").send_keys("1234")
        self.driver.find_element(By.CSS_SELECTOR, "p:nth-child(3)").click()
        self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
        self.driver.find_element(By.CSS_SELECTOR, ".user-avatar").click()
        self.driver.find_element(By.LINK_TEXT, "Edit Profile").click()
        self.driver.find_element(By.ID, "id_first_name").click()
        self.driver.find_element(By.ID, "id_first_name").click()
        self.driver.find_element(By.ID, "id_first_name").send_keys("Martin")
        self.driver.find_element(By.ID, "id_last_name").send_keys("Praguer")
        self.driver.find_element(By.ID, "id_email").click()
        self.driver.find_element(By.ID, "id_email").send_keys("martin.praguer@gmail.com")
        self.driver.find_element(By.ID, "id_city").send_keys("Břeclav")
        self.driver.find_element(By.ID, "id_address").send_keys("Sušilova 11")
        self.driver.find_element(By.ID, "id_zip_code").send_keys("69003")
        self.driver.find_element(By.CSS_SELECTOR, "button:nth-child(9)").click()
