# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestTestaddauction():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_testaddauction(self):
        self.driver.get("http://127.0.0.1:8000/")
        time.sleep(2)  # Zpomalení pro vizuální kontrolu

        self.driver.set_window_size(1200, 910)
        time.sleep(2)  # Zpomalení

        self.driver.find_element(By.LINK_TEXT, "Login").click()
        time.sleep(2)  # Zpomalení

        self.driver.find_element(By.ID, "id_username").send_keys("1234")
        self.driver.find_element(By.ID, "id_password").send_keys("1234")
        time.sleep(2)  # Zpomalení

        self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
        time.sleep(3)  # Zpomalení po přihlášení

        self.driver.find_element(By.LINK_TEXT, "Add auction").click()
        time.sleep(2)  # Zpomalení po přechodu na stránku pro přidání aukce

        self.driver.find_element(By.ID, "id_name_auction").send_keys("Martin")
        time.sleep(1)  # Zpomalení

        self.driver.find_element(By.ID, "id_category").click()
        dropdown = self.driver.find_element(By.ID, "id_category")
        dropdown.find_element(By.XPATH, "//option[. = 'Paintings']").click()
        time.sleep(2)  # Zpomalení

        self.driver.find_element(By.ID, "id_description").send_keys("aukce")
        time.sleep(1)  # Zpomalení

        self.driver.find_element(By.ID, "id_start_price").send_keys("1000")
        time.sleep(1)  # Zpomalení

        self.driver.find_element(By.ID, "id_minimum_bid").send_keys("1")
        time.sleep(1)  # Zpomalení

        # Nahrání souboru
        self.driver.find_element(By.ID, "id_images").send_keys(
            "C:\\Users\\PraguerNTBK\\Desktop\\Auction gallery -ořez pro favicon.gif")
        time.sleep(2)  # Zpomalení po nahrání obrázku

        self.driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        time.sleep(3)  # Zpomalení pro vizuální kontrolu po odeslání formuláře
