"""
Django settings for aukce project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-d66msvck1rkc#jl-4#dj8l39lpyv9x23wk2d$2_fcf7%q0%*^@'

# SECURITY WARNING: don't run with debug turned on in production!

DEBUG = "True"
# DEBUG = os.environ.get("DJANGO_DEBUG", "False") == "True"

# ALLOWED_HOSTS = []
ALLOWED_HOSTS = os.environ.get("DJANGO_ALLOWED_HOSTS", "").split(",")

CSRF_TRUSTED_ORIGINS = [
    'https://auction-gallery.cz',
    'https://auction-gallery.cz'
]

# SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    'django.contrib.humanize',
    'viewer',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'aukce.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'viewer/templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'viewer.cart_context.cart_count'
            ],
        },
    },
]

WSGI_APPLICATION = 'aukce.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LOGIN_REDIRECT_URL = 'index'
LOGOUT_REDIRECT_URL = 'index'


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'


TIME_ZONE = 'Europe/Prague'  # nebo jiná časová zóna podle potřeby
USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/



# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# URL prefix pro statické soubory
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / "staticfiles"

# Cesta ke složkám s vlastními statickými soubory (např. CSS, JS, obrázky)
STATICFILES_DIRS = [
    BASE_DIR / "static" # BASE_DIR / "viewer/static",  # nebo os.path.join(BASE_DIR, 'static') v závislosti na verzi Django
]

# Konečné místo, kam se zkopírují všechny statické soubory při spuštění příkazu collectstatic

  # nebo os.path.join(BASE_DIR, 'staticfiles')


MEDIA_URL = '/media/'  # URL pro přístup k mediálním souborům (např. obrázkům)
# MEDIA_ROOT = BASE_DIR / 'media'  # Fyzická cesta k uložení mediálních souborů
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': 'redis://0.0.0.0:8080',
        'TIMEOUT': 1,  # Změňte hodnotu na nižší pro častější obnovu cache
    },
    'secondary': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': 'redis://127.0.0.1:8000',  #většinou :6379 # Druhá Redis instance (jiný port nebo databáze)
        'TIMEOUT': 1,  # Cache timeout v sekundách
    }
}

STRIPE_PUBLIC_KEY = 'váš veřejný klíč ze Stripe'
STRIPE_SECRET_KEY = 'váš tajný klíč ze Stripe'

STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"